import { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'bulma/css/bulma.css'

export default function Home() {
  const [error, setError] = useState('')
  return (
    <div>
      <Head>
        <title>Lottery dApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <nav className="navbar mt-4 mb-4">
          <div className="container">
            <div className="navbar-brand">
              <h1>Lottery dApp</h1>
            </div>
            <div className="navbar-end">
                <button className="button is-link">Connect Wallet</button>
            </div>
          </div>
        </nav>
        <div className="container">
          <section className="mt-5">
            <div class="columns">
              <div className="column is-two-thirds">
                <section className="mt-5">
                  <p className={styles.description}>
                    Enter the lottery by sending 2 Eth:
                  </p>
                  <button className="button is-link is-large is-light mt-3">Play now</button>
                  <div className="container has-text-danger">
                    <p>{error}</p>
                </div>
                </section>
                <section className="mt-5"></section>
                <section className="mt-5">
                  <p className={styles.description}>
                    <b>Admin only:</b> Pick winner
                  </p>
                  <button className="button is-primary is-large is-light mt-3">Pick winner</button>
                  <div className="container has-text-danger">
                    <p>{error}</p>
                </div>
                </section>
              </div>
              <div className="column is-one-third">
                <section className="mt-5">
                  <div class="card">
                    <div class="card-content">
                      <div class="content">
                        <h2>Lottery History</h2>
                        <div className="history-entry">
                          <div>Lottery #1 winner:</div>
                          <div>
                            <a href="https://etherscan.io/address/0x484F62a1A508107F39633C37c9071d68b8528fe5" target="_bank">
                              0x484F62a1A508107F39633C37c9071d68b8528fe5
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <section className="mt-5">
                  <div class="card">
                    <div class="card-content">
                      <div class="content">
                        <h2>Players (1)</h2>
                        <div>
                          <a href="https://etherscan.io/address/0x484F62a1A508107F39633C37c9071d68b8528fe5" target="_bank">
                            0x484F62a1A508107F39633C37c9071d68b8528fe5
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <section className="mt-5">
                  <div class="card">
                    <div class="card-content">
                      <div class="content">
                        <h2>Pot</h2>
                        <p>10 Ether</p>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </section>
        </div>
      </div>

      <footer className={styles.footer}>
        <p>&copy; 2022 Block Explorer</p>
      </footer>
    </div>
  )
}
